version: "2"
services:
  web:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: andresvidal/rpi3-mongodb3
    ports:
    - "27017:27017"
    command: bash -c "mongod --repair && mongod"
  rabbitmq:
    image: rabbitmq
    ports:
    - "5672:5672"